fix: ignore failed chmod

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -22,7 +22,7 @@ IMAGE_DIR="$CACHE_PATH/$(dirname "$IMAGE")"
 IMAGE_FULLPATH="$CACHE_PATH/$IMAGE"
 
 mkdir -p $IMAGE_DIR
-chmod 775 -R "$CACHE_PATH"
+chmod 775 -R "$CACHE_PATH" || echo "We failed to chmod but we are ignoring it"
 if [ ! -f "$IMAGE_FULLPATH" ]; then
 	srun --ntasks=1 --mem=0 \
 		--container-image="$IMAGE" \
